CREATE TABLE `flights` (
  `uid` int(11) default NULL,
  `src_apid` int(11) default NULL,
  `src_time` time default NULL,
  `dst_apid` int(11) default NULL,
  `distance` int(11) default NULL,
  `code` text,
  `seat` text,
  `seat_type` text,
  `class` text,
  `reason` text,
  `plid` int(11) default NULL,
  `alid` int(11) default NULL,
  `trid` int(11) default NULL,
  `fid` int(11) NOT NULL auto_increment,
  `duration` time default NULL,
  `registration` text,
  `note` text,
  `upd_time` datetime default NULL,
  `opp` char(1) default 'N',
  `src_date` date default NULL,
  `mode` char(1) default 'F',
  PRIMARY KEY  (`fid`),
  KEY `src_apid` (`src_apid`),
  KEY `dst_apid` (`dst_apid`),
  KEY `plid` (`plid`),
  KEY `alid` (`alid`),
  KEY `trid` (`trid`),
  KEY `uid` (`uid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;